dist: focal

matrix:
  include:
    - language: node_js
      node_js: "12"
      before_install:
        - cd web
      install:
        - npm install
      script:
        - npm run test:unit

    - language: python
      python: "3.8"
      services:
        - redis

      addons:
        postgresql: "13"
        apt:
          packages:
            - postgresql-13

      before_script:
        - psql -c 'CREATE DATABASE travisci;' -U postgres
        - psql -c "CREATE USER travisci WITH PASSWORD 'travisSuperSekret6645';" -U postgres
        - psql -c 'GRANT ALL PRIVILEGES ON DATABASE travisci TO travisci;' -U postgres
        - psql -c 'ALTER USER travisci CREATEDB;' -U postgres

      before_install:
        - cd api/tacticalrmm

      install:
        - pip install --no-cache-dir --upgrade pip
        - pip install --no-cache-dir setuptools==49.6.0 wheel==0.35.1
        - pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

      script:
        - coverage run manage.py test -v 2

      after_success:
        - coveralls
